export const VERIFY_USER = 'VERIFY_USER';
export const CONNECT_USER_TO_ROOM = 'CONNECT_USER_TO_ROOM';
export const UPDATE_USERS_IN_ROOM = 'UPDATE_USERS_IN_ROOM';
export const DISCONNECT_USER_FROM_ROOM = 'DISCONNECT_USER_FROM_ROOM';
export const LOGOUT = 'LOGOUT';

export const CHANGE_ACTIVE_ROOM = 'CHANGE_ACTIVE_ROOM';
export const ORDER_ROOMS_LEFT = 'ORDER_ROOMS_LEFT';
export const ORDER_ROOMS_RIGHT = 'ORDER_ROOMS_RIGHT';
export const DELETE_ROOM = 'DELETE_ROOM';

export const APPLY_OPTIONS = 'APPLY_OPTIONS';

export const ERROR_RESET = 'ERROR_RESET';
export const SET_ERROR = 'SET_ERROR';

export const SEND_MESSAGE = 'SEND_MESSAGE';
export const SET_MESSAGES = 'SET_MESSAGES';

export const SEARCH_STRING = 'SEARCH_STRING';
